#include "Actions.hpp"
#include "Main.hpp"
#include "config/Config.hpp"
#include "pipeline/NodeRegistry.hpp"

#include <imgui.h>
#include "ImGuiNotify_MOD.hpp"
#include "../fonts/IconFontAwesome5_Unique.h"

#include <mutex>
#include <cstring>

void UIComponents_Actions::subUI_ActionList()
{
    if (ImGui::BeginChild("Actions_List", ImVec2(0, 0), ImGuiWindowFlags_AlwaysAutoResize))
    {
        const NodeRegistry& reg = NodeRegistry::getInstance();
        const auto categories   = reg.listCategories();

        for (const auto& cat : categories)
        {
            if (ImGui::CollapsingHeader(cat.c_str(), ImGuiTreeNodeFlags_DefaultOpen))
            {
                for (const NodeDescriptor* d : reg.listByCategory(cat))
                {
                    ImGui::PushStyleVar(ImGuiStyleVar_ButtonTextAlign, ImVec2(0.1f, 0.5f)); // Button text align at left, with slight indent
                    const ImVec4 bg = ImGui::GetStyle().Colors[ImGuiCol_WindowBg];
                    const ImVec4 btnOrigColor = ImGui::GetStyle().Colors[ImGuiCol_Button];    // Use original default color for list's hover color
                    ImGui::PushStyleColor(ImGuiCol_Button, bg);
                    ImGui::PushStyleColor(ImGuiCol_ButtonHovered, btnOrigColor);

                    if (ImGui::Button(d->displayName.c_str(), ImVec2(ImGui::GetContentRegionAvail().x, 0)))
                    {
                        try 
                        {
                            auto node = NodeRegistry::getInstance().create(d->id);
                            {
                                std::scoped_lock lock(app->nodeChainMutex);
                                app->nodeChain.emplace_back(std::move(node));
                            }
                        }
                        catch (const std::exception& e)
                        {
                            LOG_ERRORF("Actions", "%s", e.what());
                            ImGui::InsertNotification({ImGuiToastType::Error, 5000, "Failed to add Action Node:\n%s", e.what()});
                        }
                    }
                    if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayNormal | ImGuiHoveredFlags_NoSharedDelay)
                        && d->description.size() > 0)
                        ImGui::SetTooltip("%s", d->description.c_str());

                    ImGui::PopStyleColor(2);
                    ImGui::PopStyleVar();
                }
            }
        }
    }
    ImGui::EndChild();
}

void UIComponents_Actions::subUI_WorkflowList()
{
    // ── Toolbar ───────────────────────────────────────────────────────────
    ImGui::PushFont(NULL, 12.0f);
    ImGui::BeginDisabled(app->nodeChain.empty());
    if (ImGui::Button(ICON_FA_SAVE "  Save Current"))
    {
        saveWfState.nameBuf[0]  = '\0';
        saveWfState.descBuf[0]  = '\0';
        std::strncpy(saveWfState.groupBuf, "", sizeof(saveWfState.groupBuf) - 1);
        saveWfState.groupBuf[sizeof(saveWfState.groupBuf) - 1] = '\0';
        saveWfState.includeOutputConfig = app->exportNodeChainWithOutputConfig;
        pendingDialog = PendingDialog::SaveWorkflow;
    }
    ImGui::EndDisabled();
    ImGui::PopFont();
    if (app->nodeChain.empty()
        && ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled | ImGuiHoveredFlags_DelayNormal))
        ImGui::SetTooltip("Add nodes to the chain first");

    ImGui::SameLine();

    ImGui::PushFont(NULL, 12.0f);
    if (ImGui::Button(ICON_FA_SYNC_ALT))
        app->WorkflowManager.scanUserWorkflow(true);
    ImGui::PopFont();
    if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayNormal))
        ImGui::SetTooltip("Rescan workflow directory");

    ImGui::Separator();

    // Drain any notifications generated by the last scan (e.g. duplicate-name renames)
    for (const auto& n : app->WorkflowManager.drainScanNotifications())
        ImGui::InsertNotification({ImGuiToastType::Warning, 8000, "%s", n.message.c_str()});

    // ── Workflow list ─────────────────────────────────────────────────────
    if (ImGui::BeginChild("Workflow_List", ImVec2(0, 0), ImGuiWindowFlags_AlwaysAutoResize))
    {
        const auto groups = app->WorkflowManager.listGroups();

        if (!app->WorkflowManager.workflowsCount())
        {
            const ImVec2 availSpace = ImGui::GetContentRegionAvail();
            const ImVec2 refTextSize = ImGui::CalcTextSize("A Workflow is a Node Chain configuration stored in Manifold");

            const ImVec2 cursorPos = ImGui::GetCursorPos();
            ImGui::SetCursorPosX(cursorPos.x + availSpace.x * 0.5f - refTextSize.x * 0.5f);
            ImGui::SetCursorPosY(cursorPos.y + availSpace.y * 0.5f - refTextSize.y * 5.2f);

            ImGui::BeginGroup();
            ImGui::TextDisabled("No Workflows in Manifold.");
            ImGui::Spacing();
            ImGui::TextDisabled("A Workflow is a Node Chain configuration stored in Manifold\n"
                                "for future use, just like \"Presets\" of audio plugins.");
            ImGui::Spacing();
            ImGui::TextDisabled("Use \"Save Current\" to add the current Node Chain as a Workflow.");
            ImGui::EndGroup();
        }
        else
        {
        // Helper lambda: renders workflow buttons + context menus for a list of descriptors
        const auto renderWorkflowItems = [&](const std::vector<const WorkflowDescriptor*>& items)
        {
            for (const WorkflowDescriptor* w : items)
            {
                ImGui::PushID(w->filePath.u8string().c_str());

                ImGui::PushStyleVar(ImGuiStyleVar_ButtonTextAlign, ImVec2(0.1f, 0.5f));
                const ImVec4 bg          = ImGui::GetStyle().Colors[ImGuiCol_WindowBg];
                const ImVec4 btnOrigColor = ImGui::GetStyle().Colors[ImGuiCol_Button];
                ImGui::PushStyleColor(ImGuiCol_Button,        bg);
                ImGui::PushStyleColor(ImGuiCol_ButtonHovered, btnOrigColor);

                if (ImGui::Button(w->name.c_str(), ImVec2(ImGui::GetContentRegionAvail().x, 0)))
                    subroutine_LoadWorkflow(*w);

                if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayNormal) && !w->description.empty())
                    ImGui::SetTooltip("%s", w->description.c_str());

                ImGui::PopStyleColor(2);
                ImGui::PopStyleVar();

                // Right-click context menu
                if (ImGui::BeginPopupContextItem("##wf_ctx"))
                {
                    if (ImGui::MenuItem("Load"))
                        subroutine_LoadWorkflow(*w);

                    ImGui::Separator();

                    if (ImGui::MenuItem("Overwrite with Current..."))
                    {
                        pendingOverwriteWorkflow = *w;
                        pendingDialog = PendingDialog::OverwriteWorkflowConfirm;
                    }

                    ImGui::Separator();

                    if (ImGui::MenuItem("Rename..."))
                    {
                        pendingRenameWorkflow = *w;
                        std::strncpy(renameWfState.nameBuf, w->name.c_str(),
                                     sizeof(renameWfState.nameBuf) - 1);
                        renameWfState.nameBuf[sizeof(renameWfState.nameBuf) - 1] = '\0';
                        pendingDialog = PendingDialog::RenameWorkflow;
                    }
                    if (ImGui::MenuItem("Change Group..."))
                    {
                        pendingChangeGrpWorkflow = *w;
                        std::strncpy(changeGrpState.groupBuf, w->group.c_str(),
                                     sizeof(changeGrpState.groupBuf) - 1);
                        changeGrpState.groupBuf[sizeof(changeGrpState.groupBuf) - 1] = '\0';
                        pendingDialog = PendingDialog::ChangeGroupWorkflow;
                    }

                    ImGui::Separator();

                    if (ImGui::MenuItem("Delete..."))
                    {
                        pendingDeleteWorkflow = *w;
                        pendingDialog = PendingDialog::DeleteWorkflowConfirm;
                    }
                    if (ImGui::MenuItem("Reveal in Explorer"))
                        subroutine_RevealWorkflow(*w);

                    ImGui::EndPopup();
                }

                ImGui::PopID();
            }
        };

        // Named groups
        for (const auto& group : groups)
        {
            if (ImGui::CollapsingHeader(group.c_str(), ImGuiTreeNodeFlags_DefaultOpen))
                renderWorkflowItems(app->WorkflowManager.listByGroup(group));
        }

        // Ungrouped items (group == "")
        const auto ungrouped = app->WorkflowManager.listByGroup("");
        if (!ungrouped.empty())
        {
            ImGui::PushStyleColor(ImGuiCol_Text, ImGui::GetStyle().Colors[ImGuiCol_TextDisabled]);
            const bool open = ImGui::CollapsingHeader("(Ungrouped)", ImGuiTreeNodeFlags_DefaultOpen);
            ImGui::PopStyleColor();
            if (open)
                renderWorkflowItems(ungrouped);
        }
        }
    }
    ImGui::EndChild();
}

void UIComponents_Actions::subroutine_LoadWorkflow(const WorkflowDescriptor& w)
{
    if (!std::filesystem::exists(w.filePath))
    {
        constexpr const char* errMsgTemplate = "Workflow file does not exist, or path is empty";
        LOG_ERRORF("Actions", errMsgTemplate);
        ImGui::InsertNotification({ImGuiToastType::Error, 5000, errMsgTemplate});
        return;
    }

    try {
        // Pass &preferences.outputConfigPref directly: if the file contains an [output]
        // section, it is applied in-place to the app's output settings (folder, format,
        // subtype, null-output). If absent, the existing settings are left unchanged.
        NodeConfig::loadNodeChain(w.filePath.u8string(), app->nodeChain, app->nodeChainMutex,
                                    app->importNodeChainWithOutputConfig ? &app->preferences.outputConfigPref : nullptr);

        // Reset drag-and-drop state since the node chain structure has changed.
        app->dragDropState.reset();

        // Validate the imported filename template if output config was applied.
        if (app->importNodeChainWithOutputConfig)
        {
            if (auto err = app->preferences.outputConfigPref.filenameTemplate.validate())
            {
                const std::string errMsg = *err;
                LOG_WARNF("Actions",
                            "Imported filename template is invalid (%s) — reset to default",
                            errMsg.c_str());
                app->preferences.outputConfigPref.filenameTemplate = FilenameTemplate::makeDefault();
                ImGui::InsertNotification({ImGuiToastType::Warning, 8000,
                    "Imported filename template is invalid:\n%s\nReset to default.",
                    errMsg.c_str()});
            }
        }

        LOG_INFOF("Actions", "Loaded workflow: %s", w.name.c_str());
        ImGui::InsertNotification({ImGuiToastType::Success, 5000, "Successfully loaded Workflow \"%s\".", w.name.c_str()});
    }
    catch (const char* err) {
        constexpr const char* errMsgTemplate = "Failed to load workflow \"%s\":\n %s";
        LOG_ERRORF("Actions", errMsgTemplate, w.name.c_str(), err);
        ImGui::InsertNotification({ImGuiToastType::Error, 5000, errMsgTemplate, w.name.c_str(), err});
    }
    catch (const std::exception& e) {
        constexpr const char* errMsgTemplate = "Failed to load workflow \"%s\":\n %s";
        LOG_ERRORF("Actions", errMsgTemplate, w.name.c_str(), e.what());
        ImGui::InsertNotification({ImGuiToastType::Error, 5000, errMsgTemplate, w.name.c_str(), e.what()});
    }
}
