// LogManager.hpp: A high-performance, versatile log manager with ring buffer.
// Code generated by Claude Sonnet 4.6.

#pragma once

#include <string>
#include <vector>
#include <mutex>
#include <functional>
#include <chrono>
#include <cstdint>
#include <atomic>
#include <optional>

// ============================================================
// LogLevel
// ============================================================

/// @brief Severity levels for log entries, ordered from least to most severe.
enum class LogLevel : uint8_t
{
    Trace = 0,  ///< Fine-grained tracing; for debug builds only
    Debug,      ///< Diagnostic information
    Info,       ///< Normal operational messages
    Warn,       ///< Warning: something unexpected but recoverable occurred
    Error,      ///< Error: a specific operation could not complete
    Fatal       ///< Fatal: unrecoverable error, process should terminate
};

// ============================================================
// LogEntry
// ============================================================

/// @brief A single immutable log record produced by LogManager.
struct LogEntry
{
    LogLevel                              level;      ///< Severity level
    std::string                           tag;        ///< Subsystem / module label (may be empty)
    std::string                           message;    ///< Log message text
    std::chrono::system_clock::time_point timestamp;  ///< Wall-clock time of the record
};

// ============================================================
// LogFilter
// ============================================================

/// @brief Composite filter criteria passed to LogManager::filter().
///
/// Defined outside LogManager to avoid the C++ restriction that prevents
/// default member initializers inside nested classes used as default arguments.
struct LogFilter
{
    std::optional<LogLevel> minLevel;          ///< Inclusive lower bound on level (unset = no lower bound)
    std::optional<LogLevel> maxLevel;          ///< Inclusive upper bound on level (unset = no upper bound)
    std::string             keyword;           ///< Substring to match in @c message; empty = no filter
    std::string             tag;               ///< Exact tag to match; empty = no filter
    bool                    caseSensitive = false; ///< Whether keyword matching is case-sensitive
};

/// @brief Thread-safe log manager backed by a power-of-two ring buffer.
///
/// When the buffer is full the oldest entry is silently overwritten
/// (ring-overwrite strategy).  All public methods are thread-safe.
///
/// ### Typical usage
/// @code
/// // Any thread, any translation unit:
/// LOG_INFO("MyTag", "Something happened");
///
/// // UI thread – check for new entries once per frame:
/// if (seq != LogManager::instance().writeSeq())
///     refresh();
/// @endcode
class LogManager
{
public:
    /// @brief Alias kept for backwards compatibility.
    using Filter = LogFilter;

    /// @brief Callback invoked after a new entry has been written (called without holding the lock).
    ///
    /// Can be used to wake up a UI thread.  The callback receives a const
    /// reference to the newly appended entry.
    using NewLogCallback = std::function<void(const LogEntry&)>;

    // ----------------------------------------------------------
    // Construction / destruction
    // ----------------------------------------------------------

    /// @brief Construct a LogManager with the given ring-buffer capacity.
    /// @param capacity Desired number of entries; rounded up to the next
    ///                 power of two, minimum 16.
    explicit LogManager(size_t capacity = 1024);
    ~LogManager() = default;

    // std::mutex is not movable/copyable – disable all special members.
    LogManager(const LogManager&)            = delete;
    LogManager& operator=(const LogManager&) = delete;
    LogManager(LogManager&&)                 = delete;
    LogManager& operator=(LogManager&&)      = delete;

    // ----------------------------------------------------------
    // Logging
    // ----------------------------------------------------------

    /// @brief Write a log entry at the specified level.
    /// @param level   Severity level.
    /// @param message Log message text.
    /// @param tag     Optional subsystem / module label.
    void log(LogLevel level, const std::string& message, const std::string& tag = "");

    /// @brief Write a printf-style formatted log entry.
    /// @param level Severity level.
    /// @param tag   Subsystem / module label.
    /// @param fmt   printf format string followed by optional arguments.
    void logf(LogLevel level, const std::string& tag, const char* fmt, ...) noexcept;

    /// @name Convenience wrappers – one per severity level
    /// @{
    void trace(const std::string& message, const std::string& tag = "");
    void debug(const std::string& message, const std::string& tag = "");
    void info (const std::string& message, const std::string& tag = "");
    void warn (const std::string& message, const std::string& tag = "");
    void error(const std::string& message, const std::string& tag = "");
    void fatal(const std::string& message, const std::string& tag = "");
    /// @}

    // ----------------------------------------------------------
    // Control
    // ----------------------------------------------------------

    /// @brief Set the minimum level that will be recorded.
    ///        Calls below this threshold are discarded immediately (no locking).
    void setMinLevel(LogLevel level);

    /// @brief Return the current minimum recording level.
    LogLevel getMinLevel() const;

    /// @brief Remove all entries from the ring buffer.
    void clear();

    // ----------------------------------------------------------
    // Queries  (all return copies; do not block concurrent writes)
    // ----------------------------------------------------------

    /// @brief Return the number of valid entries currently in the buffer.
    size_t size() const;

    /// @brief Return @c true if the buffer contains no entries.
    bool   empty() const;

    /// @brief Monotonically increasing write counter.
    ///
    /// Incremented after every successful log() call.  Fully lock-free;
    /// a UI thread can compare this value each frame to detect new entries
    /// without paying the cost of acquiring the mutex.
    uint64_t writeSeq() const noexcept;

    /// @brief Return the ring-buffer capacity (always a power of two).
    size_t capacity() const;

    /// @brief Return all valid entries in chronological order (oldest first).
    std::vector<LogEntry> getAll() const;

    /// @brief Return the @p n most recent entries (or all entries if fewer than @p n exist).
    std::vector<LogEntry> getRecent(size_t n) const;

    /// @brief Return entries whose level falls within [@p minLevel, @p maxLevel].
    std::vector<LogEntry> filterByLevel(LogLevel minLevel,
                                        LogLevel maxLevel = LogLevel::Fatal) const;

    /// @brief Return entries whose message contains @p keyword.
    /// @param caseSensitive When @c false (default) the comparison is case-insensitive.
    std::vector<LogEntry> filterByKeyword(const std::string& keyword,
                                          bool caseSensitive = false) const;

    /// @brief Return entries whose tag exactly matches @p tag.
    std::vector<LogEntry> filterByTag(const std::string& tag) const;

    /// @brief Return entries that satisfy all criteria in @p f.
    std::vector<LogEntry> filter(const Filter& f) const;

    // ----------------------------------------------------------
    // Statistics
    // ----------------------------------------------------------

    /// @brief Return per-level entry counts.
    ///
    /// The returned array has six elements indexed by the underlying value of
    /// @c LogLevel (0 = Trace … 5 = Fatal).
    std::array<size_t, 6> levelCounts() const;

    // ----------------------------------------------------------
    // Export
    // ----------------------------------------------------------

    /// @brief Serialize all entries to a multi-line string.
    ///
    /// Format per line: @c [HH:MM:SS.mmm] [LEVEL] [TAG] message
    std::string exportToString() const;

    /// @brief Serialize entries matching @p f to a multi-line string.
    ///
    /// Format per line: @c [HH:MM:SS.mmm] [LEVEL] [TAG] message
    std::string exportToString(const Filter& f) const;

    // ----------------------------------------------------------
    // Callback
    // ----------------------------------------------------------

    /// @brief Register a callback that fires after each new entry is appended.
    ///
    /// The callback is invoked outside the internal mutex to prevent deadlocks.
    /// Pass @c nullptr or call clearNewLogCallback() to unregister.
    void setNewLogCallback(NewLogCallback callback);

    /// @brief Unregister the currently registered callback.
    void clearNewLogCallback();

    // ----------------------------------------------------------
    // Global default instance (process-wide singleton)
    // ----------------------------------------------------------

    /// @brief Return the process-wide default LogManager.
    ///
    /// All modules can share this instance by calling @c LogManager::instance().
    /// Independent LogManager objects can still be constructed for unit-test
    /// isolation.
    ///
    /// @note The instance is constructed on the first call using
    ///       @p initialCapacity.  Subsequent calls ignore that argument.
    ///       To use a custom capacity, call @c instance(capacity) once at
    ///       program startup before any other log call.
    static LogManager& instance(size_t initialCapacity = 1024);

    // ----------------------------------------------------------
    // Static utilities
    // ----------------------------------------------------------

    /// @brief Return the full name of @p level (e.g. @c "TRACE", @c "DEBUG").
    static const char* levelToString(LogLevel level);

    /// @brief Return the three-letter abbreviation for @p level (e.g. @c "TRC", @c "DBG").
    static const char* levelToShortString(LogLevel level);

private:
    /// Round @p n up to the nearest power of two; result is at least @p minVal.
    static size_t nextPow2(size_t n, size_t minVal = 16);

    /// Copy all valid entries in chronological order into @p out.  Caller must hold @c m_mutex.
    void copyAllLocked(std::vector<LogEntry>& out) const;

    /// Return @c true if @p entry satisfies all criteria in @p f.  Caller must hold @c m_mutex.
    static bool matchesFilter(const LogEntry& entry, const Filter& f);

    // ---- Data members ----
    size_t                    m_capacity;      ///< Ring-buffer capacity (always a power of two)
    size_t                    m_mask;          ///< @c m_capacity - 1; used for bitwise index wrap
    std::vector<LogEntry>     m_buffer;        ///< Pre-allocated ring buffer

    size_t                    m_head  = 0;     ///< Next write slot (monotonically increasing; use @c & @c m_mask to index)
    size_t                    m_count = 0;     ///< Number of valid entries in [0, m_capacity]

    std::atomic<uint8_t>      m_minLevel{static_cast<uint8_t>(LogLevel::Trace)};
    std::atomic<uint64_t>     m_writeSeq{0};   ///< Incremented on each write; used by the UI for dirty-checking

    mutable std::mutex        m_mutex;
    NewLogCallback            m_callback;
};

// ============================================================
// Convenience macros — write to the global default instance.
//
// Usage:  LOG_INFO("MyTag", "message")   or   LOG_INFOF("MyTag", "%d items", n)
// Accepts both std::string and string literals.
// ============================================================

/// @name Plain-string message macros
/// @{
#define LOG_TRACE(tag, msg) LogManager::instance().trace((msg), (tag))
#define LOG_DEBUG(tag, msg) LogManager::instance().debug((msg), (tag))
#define LOG_INFO(tag, msg)  LogManager::instance().info ((msg), (tag))
#define LOG_WARN(tag, msg)  LogManager::instance().warn ((msg), (tag))
#define LOG_ERROR(tag, msg) LogManager::instance().error((msg), (tag))
#define LOG_FATAL(tag, msg) LogManager::instance().fatal((msg), (tag))
/// @}

/// @name Printf-style format-string message macros
/// @{
#define LOG_TRACEF(tag, ...) LogManager::instance().logf(LogLevel::Trace, (tag), __VA_ARGS__)
#define LOG_DEBUGF(tag, ...) LogManager::instance().logf(LogLevel::Debug, (tag), __VA_ARGS__)
#define LOG_INFOF(tag, ...)  LogManager::instance().logf(LogLevel::Info,  (tag), __VA_ARGS__)
#define LOG_WARNF(tag, ...)  LogManager::instance().logf(LogLevel::Warn,  (tag), __VA_ARGS__)
#define LOG_ERRORF(tag, ...) LogManager::instance().logf(LogLevel::Error, (tag), __VA_ARGS__)
#define LOG_FATALF(tag, ...) LogManager::instance().logf(LogLevel::Fatal, (tag), __VA_ARGS__)
/// @}
