#include "Main.hpp"

#include <imgui.h>
#include <chrono>
#include <cstdio>
#include <ctime>
#include <string>

// Code generated by Claude Sonnet v4.6.

// ============================================================
// Internal utilities
// ============================================================

namespace {

// Format timestamp to "HH:MM:SS.mmm"
static std::string fmtTimestamp(const std::chrono::system_clock::time_point& tp)
{
    using namespace std::chrono;
    auto t  = system_clock::to_time_t(tp);
    auto ms = duration_cast<milliseconds>(tp.time_since_epoch()) % 1000;
    std::tm tm_buf{};
#ifdef _WIN32
    localtime_s(&tm_buf, &t);
#else
    localtime_r(&t, &tm_buf);
#endif
    char buf[16];
    std::snprintf(buf, sizeof(buf), "%02d:%02d:%02d.%03d",
                  tm_buf.tm_hour, tm_buf.tm_min, tm_buf.tm_sec,
                  static_cast<int>(ms.count()));
    return buf;
}

// Text colors for each log level
static ImVec4 levelColor(LogLevel level)
{
    switch (level)
    {
        case LogLevel::Trace: return {0.55f, 0.55f, 0.55f, 1.0f};  // Gray
        case LogLevel::Debug: return {0.40f, 0.80f, 1.00f, 1.0f};  // Light blue
        case LogLevel::Info:  return {1.00f, 1.00f, 1.00f, 1.0f};  // White
        case LogLevel::Warn:  return {1.00f, 0.85f, 0.00f, 1.0f};  // Yellow
        case LogLevel::Error: return {1.00f, 0.40f, 0.40f, 1.0f};  // Red
        case LogLevel::Fatal: return {1.00f, 0.20f, 0.60f, 1.0f};  // Magenta
        default:              return {1.00f, 1.00f, 1.00f, 1.0f};
    }
}

} // anonymous namespace

// ============================================================
// ManifoldApp::UI_Log
// ============================================================

void ManifoldApp::UI_Log()
{
    auto& logger = LogManager::instance();

    // Dirty check
    // writeSeq() is atomic read, completely lock-free. Most frames skip here directly with no copy overhead.
    uint64_t currentSeq = logger.writeSeq();
    if (currentSeq != logUI.lastSeq || logUI.dirty)
    {
        static const LogLevel s_levelTable[] = {
            LogLevel::Trace, LogLevel::Debug, LogLevel::Info,
            LogLevel::Warn,  LogLevel::Error, LogLevel::Fatal
        };

        LogFilter f;
        f.minLevel = s_levelTable[logUI.minLevelIdx];
        if (logUI.keywordBuf[0] != '\0')
            f.keyword = logUI.keywordBuf;

        logUI.snapshot = logger.filter(f);
        logUI.dirty    = false;

        // Only trigger auto-scroll when new logs arrive; don't scroll when filter conditions change (preserve reading position)
        if (currentSeq != logUI.lastSeq && logUI.autoScroll)
            logUI.scrollToEnd = true;

        logUI.lastSeq = currentSeq;
    }

    if (ImGui::BeginChild("Log Viewer"))
    {
        // Toolbar
        {
            ImGui::AlignTextToFramePadding();

            // Minimum level filter
            ImGui::Text("Level:");
            ImGui::SameLine();
            ImGui::SetNextItemWidth(80.0f);
            if (ImGui::Combo("##minlevel", &logUI.minLevelIdx,
                            "Trace\0Debug\0Info\0Warn\0Error\0Fatal\0\0"))
                logUI.dirty = true;

            // Keyword filter
            ImGui::SameLine(0, 12);
            ImGui::Text("Filter:");
            ImGui::SameLine();
            ImGui::SetNextItemWidth(200.0f);
            if (ImGui::InputText("##keyword", logUI.keywordBuf, sizeof(logUI.keywordBuf)))
                logUI.dirty = true;

            // Clear
            ImGui::SameLine(0, 12);
            if (ImGui::Button("Clear"))
            {
                logger.clear();
                logUI.snapshot.clear();
                logUI.selectedIdx = -1;
                logUI.lastSeq     = logger.writeSeq();
                logUI.dirty       = false;
            }

            // Auto-scroll toggle
            ImGui::SameLine();
            ImGui::Checkbox("Auto-scroll", &logUI.autoScroll);

            // Statistics: current displayed count / total count, and counts for each high-priority level
            auto counts = logger.levelCounts();
            ImGui::SameLine(0, 16);
            ImGui::TextDisabled("Showing %zu / %zu  |  W:%zu  E:%zu  F:%zu",
                logUI.snapshot.size(),
                logger.size(),
                counts[static_cast<size_t>(LogLevel::Warn)],
                counts[static_cast<size_t>(LogLevel::Error)],
                counts[static_cast<size_t>(LogLevel::Fatal)]);
        }

        ImGui::Separator();

        // Log list
        if (ImGui::BeginChild("Log View Area", ImVec2(0, 0), false,
                            ImGuiWindowFlags_HorizontalScrollbar))
        {
            // ListClipper: only calls rendering code for currently visible rows, performance unaffected by entry count in large buffers
            ImGuiListClipper clipper;
            clipper.Begin(static_cast<int>(logUI.snapshot.size()));
            while (clipper.Step())
            {
                for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i)
                {
                    const LogEntry& e = logUI.snapshot[i];

                    // Format as single line: [HH:MM:SS.mmm] [LVL] [TAG] message
                    char line[1024];
                    if (e.tag.empty())
                        std::snprintf(line, sizeof(line), "[%s] [%s] %s",
                                    fmtTimestamp(e.timestamp).c_str(),
                                    LogManager::levelToShortString(e.level),
                                    e.message.c_str());
                    else
                        std::snprintf(line, sizeof(line), "[%s] [%s] [%s] %s",
                                    fmtTimestamp(e.timestamp).c_str(),
                                    LogManager::levelToShortString(e.level),
                                    e.tag.c_str(),
                                    e.message.c_str());

                    ImGui::PushID(i);
                    ImGui::PushStyleColor(ImGuiCol_Text, levelColor(e.level));

                    bool selected = (logUI.selectedIdx == i);
                    if (ImGui::Selectable(line, selected,
                                        ImGuiSelectableFlags_SpanAllColumns |
                                        ImGuiSelectableFlags_AllowOverlap))
                        logUI.selectedIdx = i;

                    ImGui::PopStyleColor();

                    // Context menu: copy entire line or copy message body only
                    if (ImGui::BeginPopupContextItem("##ctx"))
                    {
                        if (ImGui::MenuItem("Copy Line"))
                            ImGui::SetClipboardText(line);
                        if (ImGui::MenuItem("Copy Message"))
                            ImGui::SetClipboardText(e.message.c_str());
                        ImGui::EndPopup();
                    }

                    ImGui::PopID();
                }
            }
            clipper.End();

            // Auto-scroll to bottom when new logs arrive
            if (logUI.scrollToEnd)
            {
                ImGui::SetScrollHereY(1.0f);
                logUI.scrollToEnd = false;
            }

            ImGui::EndChild();
        }

        ImGui::EndChild();
    }
}
